### ISSUE TITLE
Prevent freeze when starting the program

### ISSUE THREAD

**Issue by pierrelasse** [DevToys-app/DevToys#1095]
### What feature or new tool do you think should be added to DevToys?

Anti freeze

### Why do you think this is needed?

So i can use the program again

### Solution/Idea

I accidentally put a very huge base64 string in the Base64 Text decoder and now i'm unable to use the program.
When i start the program, it freezes after ~0.7 seconds.
Since this is a stupid microsoft app, the app files are all over the place and i cant find where this could be saved to delete it.

Current solution?: Uninstall program and hope it deletes settings. Reinstall.

**Comment by KLXYinc** [comment]
same happened to me

**Comment by veler** [comment]
Hello,
What version are you using? This is already addressed in DevToys 2.0. We succeed to treat 100MB files without freezing.

**Comment by pierrelasse** [comment]
> Hello,
> 
> What version are you using? This is already addressed in DevToys 2.0. We succeed to treat 100MB files without freezing.

I just installed it today so i guess the latest version.

**Comment by veler** [comment]
I see, so probably version 1.0.13.0 (version 2.0 isn't released yet).
I will close this issue as it's fixed in 2.0

**Comment by sivadasrajan** [comment]
It is still freezing at startup and at random for me in 2.0-preview.8 
I like the software but its basically unusable.
Im running it on Debian 12
